### ISSUE TITLE
AEM 6.1 Support?

### ISSUE THREAD

**Issue by zoosky** [Cognifide/SecureCQ#3]
Is this planned?

**Comment by trekawek** [comment]
Hi @zoosky, I think the SecureCQ should work on AEM 6.1. Are you experiencing any issues?

**Comment by yagyesh11235** [comment]
@zoosky @trekawek : i was able to build the package without any issues on aem 6.1

![image](https://cloud.githubusercontent.com/assets/3796564/11866212/95a023d2-a4cf-11e5-90cf-2c7b2483d815.png)

**Comment by trekawek** [comment]
@yagyesh11235, thanks for the comment. Therefore I'm closing the issue.
